apiVersion: fedlearner.k8s.io/v1alpha1
kind: FLApp
metadata:
  name: abnormal
  namespace: follower
spec:
  flReplicaSpecs:
    Master:
      pair: true
      replicas: 2
      restartPolicy: Never
      template:
        spec:
          restartPolicy: Never # required
          containers:
            - env:
              - name: APPLICATION_ID
                value: abnormal
              - name: HOST_IP
                valueFrom:
                  fieldRef:
                    fieldPath: status.hostIP
              image: nicolaka/netshoot
              imagePullPolicy: IfNotPresent
              name: tensorflow # default
              ports:
                - containerPort: 50051
                  name: flapp-port # default
              resources:
                limits:
                  cpu: 4000m
                  memory: 4Gi
                requests:
                  cpu: 4000m
                  memory: 4Gi
              command: ["bash"]
              args: ["-c", "sleep 1m"]
    PS:
      pair: false
      replicas: 1
      restartPolicy: Never
      template:
        spec:
          restartPolicy: Never # required
          containers:
            - env:
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: HOST_IP
                valueFrom:
                  fieldRef:
                    fieldPath: status.hostIP
              image: nicolaka/netshoot
              imagePullPolicy: IfNotPresent
              name: tensorflow # default
              ports:
                - containerPort: 50051
                  name: flapp-port # default
              resources:
                limits:
                  cpu: 4000m
                  memory: 4Gi
                requests:
                  cpu: 4000m
                  memory: 4Gi
              command: ["bash"]
              args: ["-c", "sleep 1m"]
    Worker:
      pair: true
      replicas: 3
      template:
        spec:
          restartPolicy: Never # required
          containers:
            - env:
              - name: APPLICATION_ID
                value: abnormal
              - name: HOST_IP
                valueFrom:
                  fieldRef:
                    fieldPath: status.hostIP
              image: nicolaka/netshoot
              imagePullPolicy: IfNotPresent
              name: tensorflow # default
              ports:
                - containerPort: 50051
                  name: flapp-port # default
              resources:
                limits:
                  cpu: 4000m
                  memory: 4Gi
                requests:
                  cpu: 4000m
                  memory: 4Gi
              command: ["bash"]
              args: ["-c", "sleep 1m && exit 1"]
  role: Follower
  peerSpecs:
    Leader:
      peerURL: flapp-operator.leader.svc.cluster.local:8100
