apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flapp-operator
  name: flapp-operator
  namespace: leader
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flapp-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flapp-operator
    spec:
      containers:
        - args:
            - --port=8100
            - --namespace=leader
            - --leader-election=true
            - --leader-election-lock-namespace=leader
            - --resync-interval=5
          command:
            - ./main
          image: fedlearner_operator:2.1.1
          imagePullPolicy: IfNotPresent
          name: flapp-operator
          ports:
            - containerPort: 8100
          resources:
            limits:
              cpu: "4"
              memory: 4Gi
            requests:
              cpu: "4"
              memory: 4Gi
      restartPolicy: Always
      serviceAccountName: flapp-operator
---
apiVersion: v1
kind: Service
metadata:
  name: flapp-operator
  namespace: leader
spec:
  selector:
    app: flapp-operator
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 8100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flapp-operator
  name: flapp-operator
  namespace: follower
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flapp-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flapp-operator
    spec:
      containers:
        - args:
            - --port=8100
            - --namespace=follower
            - --leader-election=true
            - --leader-election-lock-namespace=follower
            - --resync-interval=5
          command:
            - ./main
          image: fedlearner_operator:2.1.1
          imagePullPolicy: IfNotPresent
          name: flapp-operator
          ports:
            - containerPort: 8100
              hostPort: 8100
          resources:
            limits:
              cpu: "4"
              memory: 4Gi
            requests:
              cpu: "4"
              memory: 4Gi
      restartPolicy: Always
      serviceAccountName: flapp-operator
---
apiVersion: v1
kind: Service
metadata:
  name: flapp-operator
  namespace: follower
spec:
  selector:
    app: flapp-operator
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 8100
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flapp-operator-follower
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flapp-operator
subjects:
  - kind: ServiceAccount
    name: flapp-operator
    namespace: follower
